- name: Install nginx server
  hosts: aws1
  become: yes

  tasks:
  - name: Update APT package index
    apt:
      update_cache: yes

  - name: Install Nginx 
    apt:
      name: nginx
      state: present

  - name: Copy HTML to deafult location
    copy:
      src: index.html 
      dest: /var/www/html/index.html
      # dest: /usr/share/nginx/html/index.html 

      # sometimes ubuntu uses this or the previous one to show live in the server
      mode: 0644 #to give the proper permission

  - name: Start Nginx 
    service:
      name: nginx
      state: started
      enabled: yes

# to run the file: sudo ansible-playbook -i inventory.yml nginx.yml
# verfiying- copy public ip and paste in browser if nginx default page comes it started


      